name: 'automated_testing_framework_server_websocket'
description: 'Websocket based server for the Automated Testing Framework driver.'
version: '2.0.0+4'
homepage: 'https://github.com/peiffer-innovations/automated_testing_framework_server_websocket'

environment: 
  sdk: '>=2.17.0 <3.0.0'

dependencies: 
  args: '^2.3.1'
  automated_testing_framework_models: '^2.0.9+4'
  json_class: '^2.1.2+8'
  logging: '^1.0.2'
  meta: '^1.7.0'
  uuid: '^3.0.6'
  web_socket_channel: '^2.2.0'

dev_dependencies: 
  test: '^1.21.4'

ignore_updates: 
  - 'async'
  - 'boolean_selector'
  - 'characters'
  - 'charcode'
  - 'collection'
  - 'clock'
  - 'fake_async'
  - 'file'
  - 'matcher'
  - 'material_color_utilities'
  - 'meta'
  - 'path'
  - 'source_span'
  - 'stack_trace'
  - 'stream_channel'
  - 'string_scanner'
  - 'term_glyph'
  - 'vector_math'
