name: 'automated_testing_framework_server_websocket'
description: 'Websocket based server for the Automated Testing Framework driver.'
version: '2.0.1'
homepage: 'https://github.com/peiffer-innovations/automated_testing_framework_server_websocket'

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  args: '^2.3.2'
  automated_testing_framework_models: '^2.0.9+16'
  json_class: '^2.1.4+1'
  logging: '^1.1.0'
  meta: '^1.7.0'
  uuid: '^3.0.7'
  web_socket_channel: '^2.3.0'

dev_dependencies:
  test: '^1.22.2'

ignore_updates:
  - 'archive'
  - 'async'
  - 'boolean_selector'
  - 'characters'
  - 'charcode'
  - 'collection'
  - 'clock'
  - 'crypto'
  - 'fake_async'
  - 'file'
  - 'matcher'
  - 'material_color_utilities'
  - 'meta'
  - 'path'
  - 'source_span'
  - 'stack_trace'
  - 'stream_channel'
  - 'string_scanner'
  - 'sync_http'
  - 'term_glyph'
  - 'test_api'
  - 'typed_data'
  - 'vector_math'
  - 'webdriver'
