name: automated_testing_framework_server_websocket
description: Websocket based server for the Automated Testing Framework driver.
version: 0.9.5+2
homepage: https://github.com/peiffer-innovations/automated_testing_framework_server_websocket

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  args: ^2.0.0
  automated_testing_framework_models: ^2.0.1
  json_class: ^2.0.0
  logging: ^1.0.1
  meta: ^1.3.0
  uuid: ^3.0.3
  web_socket_channel: ^2.0.0

# dependency_overrides:
#   automated_testing_framework_models:
#     path: ../automated_testing_framework_models

dev_dependencies:
  test: any
