name: automated_testing_framework_server_websocket
description: Websocket based server for the Automated Testing Framework driver.
version: 2.0.0
homepage: https://github.com/peiffer-innovations/automated_testing_framework_server_websocket

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  args: ^2.3.1
  automated_testing_framework_models: ^2.0.9
  json_class: ^2.1.2+4
  logging: ^1.0.2
  meta: ^1.7.0
  uuid: ^3.0.6
  web_socket_channel: ^2.2.0

# dependency_overrides:
#   automated_testing_framework_models:
#     path: ../automated_testing_framework_models

dev_dependencies:
  test: ^1.21.1
