name: Dart Publisher

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Validate
        uses: peiffer-innovations/actions-flutter-validate@v1.1.2
        with:
          flutter_package: false
      - name: Publish
        uses: peiffer-innovations/actions-pub-publish@v1.0.1
        with:
          credentials: ${{ secrets.CREDENTIALS_JSON }}
