name: Dart Publisher

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: dart pub upgrade
      - name: Dart Analyzer
        run: dart analyze lib
      - name: Code Format
        run: dart format --set-exit-if-changed lib test
      - name: Run tests
        run: dart test
      - name: Publish
        uses: peiffer-innovations/actions-pub-publish@v1.0.1
        with:
          credentials: ${{ secrets.CREDENTIALS_JSON }}
